services:
  - type: web
    name: off-the-wall
    env: python
    buildCommand: "./build.sh && python manage.py migrate" # Combine build and migrate commands
    startCommand: "gunicorn the_wall.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: off-the-wall-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
    plan: free

databases:
  - name: off-the-wall-db
    plan: free
