# Generated by Django 5.2 on 2025-04-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall_message',
            name='content',
            field=models.TextField(),
        ),
    ]
